name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install avr-gcc
      run: sudo apt install -y gcc-avr avr-libc
      
    - name: build project
      run: make

    #- name: make debug
    #  run: make debug

    - name: make disasm
      run: make disasm

    - name: output disasm listing
      run: cat autolight.lss
